### ISSUE TITLE
Improved/Advaned Core using raw itemstack input instead of oredict.

### ISSUE THREAD

**Issue by ElektroKill** [ZelGimi/supersolarpanels#10]
Hello, the recipe for the Improved/Advanced core uses uranium ingot but it uses a raw ItemStack ingredient meaning that only the one from this mod will work. It is recommended to use the OreDictioanry ingredient so that other mods' uranium ingots will work fine with the recipe. I am quite positive that this was an error on your side as the Irradiant Uranium recipe uses the OreDictionary ingredient.

Faulty line: https://github.com/ZelGimi/supersolarpanels/blob/95b4750d96671eb19155dba86fdb6cb4785ce3ad/src/main/java/com/denfop/ssp/SPPRecipes.java#L48

I hope you can fix this issue,
Thanks in advance!

**Comment by ijo42** [comment]
yeah, it's fixed by 388cd767126f485f2a3a2d70924c327c5ea9e367(1.12.2-dev), but i couldn't merge it to main branch, testers unavailable.
may try fix w/ build artifacts from https://github.com/ZelGimi/supersolarpanels/runs/1964058363

**Comment by ZelGimi** [comment]
Solved
