### ISSUE TITLE
1.7.10 Кик с сервера

### ISSUE THREAD

**Issue by xmssss** [ZelGimi/supersolarpanels#11]
Билд последний с курсфоржа на эту дату. Суть проста: На примере продвинутой электрической печи. Ставим печь, запускаем процесс плавки и... включаем\отключаем ресурспак, любой. Кикает с такой ошибкой: https://www.pastery.net/fevhte/

**Comment by ZelGimi** [comment]
Вы используете 1.5RC2FIX?

**Comment by xmssss** [comment]
> Вы используете 1.5RC2FIX?

Да. Я же сказал, что последняя актуальная версия с курсофржа на момент написания ишшуи

**Comment by ZelGimi** [comment]
в 1.5RC3 были переписаны механизмы ,обновление 1.5RC3 планируется выпустить 7.03.

**Comment by xmssss** [comment]
Ну если там пофикшено, то закрывайте. Мое дело сообщить)

**Comment by ZelGimi** [comment]
Спасибо)
