### ISSUE TITLE
SSP 1.7.10 need cofhcore.

### ISSUE THREAD

**Issue by Pilad** [ZelGimi/supersolarpanels#13]
The mod requires a cofhcore. This is normal? But why, I do not understand. EU energy is used right there. Why integration with RF energy? According to the logs, this is something related to recipes. Can this strange addiction to cofhcore be removed? 
https://pastebin.com/j5pFheiW

import cofh.lib.util.helpers.ItemHelper;

      Recipes.advRecipes.addRecipe(new ItemStack(SSPItem.QuantumItems9, 1), new Object[] { 
    		  " D ","BAB"," C ", Character.valueOf('A'), Ic2Items.advancedCircuit, Character.valueOf('B'), new ItemStack(SSPItem.nanoBox,1), Character.valueOf('C'), ItemHelper.getOreName(new ItemStack(SSPItem.nickel)), Character.valueOf('D'), 
    		  SSPItem.compresscarbon });

**Comment by Pilad** [comment]
https://github.com/ZelGimi/supersolarpanels/commit/0e6e885148d357e9b08a28d9157996fd46a1c384#diff-4478dc5493eb09727482515407a4ae8592504366ce6c314e3689310e34f54898

**Comment by ZelGimi** [comment]
solved
