### ISSUE TITLE
[1.7.10] Cant build source

### ISSUE THREAD

**Issue by Dream-Master** [ZelGimi/supersolarpanels#2]
I try to build the lastest source in your 1.7.10 branch but i got an error.

Error:
https://gist.github.com/Dream-Master/52ef81c08972ec430df6d44f16e8430f

Any idea ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/104088916-8cf7e780-526a-11eb-88e5-5f50d1e33cd5.png)

**Comment by Dream-Master** [comment]
same with gradle 4.4.1

**Comment by ijo42** [comment]
at first, you must not change gradle wrapper
next, what commit you use?
try to checkout de2115102bedd62a0bd01726260168aa1e2c73a4

**Comment by Dream-Master** [comment]
the lastest source incluse this commit from today
I using for all my 1.7.10 project gradle 4.4.1 but i downgrade to 2.6 
same error

**Comment by nyshokk** [comment]
@Dream-Master i have same error, he say: "Just remove 3 files", but it's also don't work, all we have that is the time to wait for fix that's shit...

**Comment by ijo42** [comment]
I'll check it

**Comment by ijo42** [comment]
Closed by #69a68f53b2542d16d330ecd0c07120e820f254ac

**Comment by Dream-Master** [comment]
Yes it builds
