### ISSUE TITLE
Spam in console v1.4-1.5 MC 1.7.10

### ISSUE THREAD

**Issue by Pilad** [ZelGimi/supersolarpanels#20]
https://pastebin.com/JW8vq5Y7

**Comment by ZelGimi** [comment]
Version 1.5RC4FIX3?If yes, then you put the storage through a specific item

**Comment by Pilad** [comment]
I built a mod from a github. He put all the energy storage systems of the machine and solar panels into the world. And after that spam appeared. Also, most of the machines do not work. for example an extractor and others.

**Comment by ZelGimi** [comment]
Actual?
