### ISSUE TITLE
RC1.5中文翻译及bug

### ISSUE THREAD

**Issue by Alexisfw** [ZelGimi/supersolarpanels#24]
降低电压/能量等级（tier）的模块没有用，配置文件内调整也没用，机器容易炸，希望增加电压机制的开关
另附中文翻译：
[zh_CN.zip](https://github.com/ZelGimi/supersolarpanels/files/6291898/zh_CN.zip)

**Comment by ZelGimi** [comment]
would you like to help with the translation for the new version?
