### ISSUE TITLE
Some Issues of 1.7.10 version

### ISSUE THREAD

**Issue by StrangeMan1580** [ZelGimi/supersolarpanels#26]
Version: 1.5RC5.3 (1.7.10)
While playing this mod I have found some non-critical issues of this version:

1. Some Nether ores (Iridium, Michalov, Spinel, Magnesium, Tungsten, Chrome, Platinum) are not generated in Nether.
2. Neutron Solarnel from main part of mod and Neutronium Solar Panel from integration with Avaritia mod have same unlocalized names, which doesn't allow to localize them separately.
![Bug 2](https://user-images.githubusercontent.com/86133978/122624985-7bcdc500-d0ab-11eb-872d-a5092df569a3.png)
3. Terrasteel Solar Panel have wrong GUI's localization.
![Bug 3](https://user-images.githubusercontent.com/86133978/122624996-8ab47780-d0ab-11eb-8e89-40b2636d6fdf.png)

**Comment by ZelGimi** [comment]
Try checking a newer version for these bugs

**Comment by StrangeMan1580** [comment]
It was **last** available version for 1.7.10 on Curse Forge at this moment.
Also english, russian and probably others .lang files have lots of mistakes like localization for deleted items and not IC2 well-formed names for rotors, plates, etc. If you don't fix them already in new version, you can download my fix for them: https://drive.google.com/drive/folders/1HgPLpZ90D2xejq8B6R_CpeOkqBzqaQDC?usp=sharing
It also contains corrected name for Avaritia's Neutronium Solar Panel (unloc. name is blockNeutroniumSolarPanel.name).

**Comment by ZelGimi** [comment]
on 1.7.10, now it's a mod to undergo refactoring, both code and visualization (localization too).Beta testing of the mod will be carried out soon, and soon there will be an update

**Comment by ZelGimi** [comment]
in the new version all bugs from the list are fixed
