### ISSUE TITLE
The mod compatibility issues

### ISSUE THREAD

**Issue by magcicada** [ZelGimi/supersolarpanels#3]
1.Paly the super solar panels with GT5u,GT++ and Ex Nihilo,I will get this error:[CR](https://pastebin.ubuntu.com/p/32sDVt34ff/)
2.Can't compatible with Wireless Solar Panels 0.47R,this is [CR](https://pastebin.ubuntu.com/p/qmgDfdYbNB/)
super solar panels version:SuperSolarPanels-1.4.3.2
GT5u version:gregtech-5.09.31
GT++ version:GT-PlusPlus-1.7.02.09
ic2 version:industrialcraft-2-2.2.827-experimental
advanced solar panel version:AdvancedSolarPanel-1.7.10-3.5.1a
ex nihilo version:Ex-Nihilo-1.38-53

**Comment by ZelGimi** [comment]
In the first screen, i don`t see mistakle of my mod version 1.4.3.2.This problem is on side on industrialcraft2.  . In the second screen, i know this bug. It fixed five days ago?but i didnt published this fix. I will publish this fix in the next update 1.5.

**Comment by ZelGimi** [comment]
fix crash with Wireless Solar Panels in 1.5. Thanks for the bug
