### ISSUE TITLE
items don't stack

### ISSUE THREAD

**Issue by charly97carlos** [ZelGimi/supersolarpanels#5]
When I install the last version of super solar panels, 1.4.3.2, when I destroy something it doesn't stack. Example, when i destroy dirt it doesn't stack with the other dirt i have in the inventory.

**Comment by ijo42** [comment]
Thats problem fixed by c123ab5, been in next release. If want get fix quickly, compile yourself!
1) Clone repo
2) `gradlew build` in cmd/sh by repo root
3) Grab `.jar` from build/libs
