### ISSUE TITLE
Chinese translation 

### ISSUE THREAD

**Issue by 1525249038** [ZelGimi/supersolarpanels#7]
super_solar_panels.machines.spectral_solar_panel=光谱太阳能
super_solar_panels.machines.singular_solar_panel=奇异太阳能
super_solar_panels.machines.admin_solar_panel=管理员太阳能
super_solar_panels.machines.photonic_solar_panel=光子太阳能
super_solar_panels.crafting.enderquantumcomponent=终极量子组件
super_solar_panels.crafting.solarsplitter=太阳光分束器
super_solar_panels.crafting.bluecomponent=蓝色光谱组件
super_solar_panels.crafting.greencomponent=绿色光谱组件
super_solar_panels.crafting.redcomponent=红色光谱组件
super_solar_panels.solar_helmets.spectral=光谱太阳能头盔
super_solar_panels.solar_helmets.singular=奇异太阳能头盔
super_solar_panels.crafting.photoniy=光合物质
super_solar_panels.crafting.photoniy_ingot=光合锭
super_solar_panels.crafting.singularcore=奇异核心
super_solar_panels.crafting.spectralcore=光谱核心
super_solar_panels.graviChestplate1=增强型量子胸甲
super_solar_panels.graviLeggins=强化量子护腿
super_solar_panels.graviBoosts=强化量子靴子
super_solar_panels.crafting.quantumitems5=光谱电路板
super_solar_panels.crafting.quantumitems4=压缩铱板
super_solar_panels.crafting.quantumitems3=量子工具箱
super_solar_panels.crafting.quantumitems2=高级铱板
super_solar_panels.crafting.nanobox=纳米工具箱
super_solar_panels.crafting.quantcore1=§6光子量子核心
super_solar_panels.crafting.quantcore2=§c管理员量子核心
super_solar_panels.crafting.enrichedsunnariumalloy2=§c富集光子阳光合金
super_solar_panels.crafting.enrichedsunnariumalloy3=§c管理员富集阳光合金
super_solar_panels.machines.molecular_transformer=粒子重组器
super_solar_panels.machines.quantum_generator=量子发生器
super_solar_panels.machines.advanced_solar_panel=高级太阳能
super_solar_panels.machines.hybrid_solar_panel=混合太阳能
super_solar_panels.machines.ultimate_solar_panel=终极混合太阳能
super_solar_panels.machines.quantum_solar_panel=量子太阳能
super_solar_panels.machines.neutronium_solar_panel=中子太阳能
super_solar_panels.crafting.sunnarium=阳光化合物
super_solar_panels.crafting.sunnarium_part=小块阳光化合物
super_solar_panels.crafting.sunnarium_alloy=富集阳光合金
super_solar_panels.crafting.irradiant_uranium=光辉铀锭
super_solar_panels.crafting.enriched_sunnarium=富集阳光化合物
super_solar_panels.crafting.enriched_sunnarium_alloy=富集阳光合金
super_solar_panels.crafting.irradiant_glass_pane=光辉玻璃板
super_solar_panels.crafting.iridium_iron_plate=铱铁合金板
super_solar_panels.crafting.reinforced_iridium_iron_plate=强化铱铁合金板
super_solar_panels.crafting.irradiant_reinforced_plate=光辉铱铁合金板
super_solar_panels.crafting.iridium_ingot=铱锭
super_solar_panels.crafting.uranium_ingot=铀锭
super_solar_panels.crafting.mt_core=MT 核心
super_solar_panels.crafting.quantum_core=量子核心

super_solar_panels.solar_helmets.advanced=高级太阳能头盔
super_solar_panels.solar_helmets.hybrid=混合太阳能头盔
super_solar_panels.solar_helmets.ultimate=终极混合太阳能头盔

super_solar_panels.crafting.sunlinse=阳光镜
super_solar_panels.crafting.nightlinse=月光镜
super_solar_panels.crafting.rainlinse=雨镜

fluid.neutron=液态中子
fluid.iridium=液态铱
fluid.Protonium=液态质子
fluid.Platium=液态铂
super_solar_panels.super_solar_panels.helmet=强化量子头盔
super_solar_panels.crafting.quantumitems6=量子电路板
itemGroup.SSPSourceTab=超级太阳能发电机(汉化文本99%来自MC百科 _Godson)
gui.text.maxStorage=最大储存量
gui.text.output=输出 eu\tick
gui.text.currentStorage=现在
tile.null.name=中子流体
ic2.graviChestplate=强化量子胸甲
super_solar_panels.crafting.enrichedsunnariumalloy4=富集质子阳光合金
super_solar_panels.crafting.depleted_proton_fuel_rod=耗尽的质子燃料棒
super_solar_panels.crafting.depleted_dual_proton_fuel_rod=耗尽的双联质子燃料棒
super_solar_panels.crafting.depleted_quad_proton_fuel_rod=耗尽的四联质子燃料棒
super_solar_panels.crafting.depleted_eit_proton_fuel_rod=耗尽的八联质子燃料棒
super_solar_panels.crafting.compresscarbon=压缩碳板
super_solar_panels.crafting.coal_chunk=压缩煤块
super_solar_panels.crafting.compresscarbonultra=压缩高级合金
super_solar_panels.spectral_battery=强化能量水晶
super_solar_panels.quantumsaber=量子剑
super_solar_panels.spectralsaber=光谱剑
super_solar_panels.twelve_heat_storage=120K冷却单元
super_solar_panels.max_heat_storage=240K冷却单元
super_solar_panels.proton_fuel_rod=质子燃料棒
super_solar_panels.dual_proton_fuel_rod=双联质子燃料棒
super_solar_panels.quad_proton_fuel_rod=四联质子燃料棒
super_solar_panels.eit_proton_fuel_rod=八联质子燃料棒
super_solar_panels.rotor_carbon1=铱转子
super_solar_panels.rotor_carbon2=高级铱转子
super_solar_panels.rotor_carbon3=光谱转子
super_solar_panels.item_ult_drill=完美电钻
super_solar_panels.item_ult_drill.mode=模式:
super_solar_panels.item_ult_drill.mode.normal=正常
super_solar_panels.item_ult_drill.mode.bigHoles=挖坑模式
super_solar_panels.item_ult_drill.mode.bigHoles1=超级挖坑模式
super_solar_panels.machines.iridiumgenerator=铱发生器
super_solar_panels.machines.transformator=强化变压器
super_solar_panels.machines.transformator1=高级变压器
super_solar_panels.machines.transformator2=终极变压器
super_solar_panels.machines.transformator3=量子变压器
super_solar_panels.machines.transformator4=光谱变压器
super_solar_panels.machines.transformator5=质子变压器
super_solar_panels.machines.advancedmfsu=强化MFSU储电箱
super_solar_panels.machines.ultimatemfsu=终极MFSU储电箱
super_solar_panels.machines.quantummfsu=量子MFSU储电箱
tile.iridium_ore.name=铱矿石
tile.iridium_block.name=铱块
tile.platium_block.name=铂金块
tile.platium_ore.name=铂矿石
super_solar_panels.crafting.advanced_core=高级核心
super_solar_panels.crafting.hybrid_core=混合核心
super_solar_panels.crafting.ultimate_core=终极核心
super_solar_panels.crafting.dust=纳米粉末
super_solar_panels.crafting.protoncore=质子核心
super_solar_panels.crafting.protonshard=质子碎片
super_solar_panels.crafting.proton=质子
super_solar_panels.crafting.neutronshard=中子碎片
super_solar_panels.crafting.neutron=中子
super_solar_panels.crafting.neutroncore=中子核心
super_solar_panels.machines.proton_solar_panel=质子太阳能

super_solar_panels.gui.input=输入:
super_solar_panels.gui.output=输出:
super_solar_panels.gui.maxOutput=最大输出:
super_solar_panels.gui.energyPerOperation=能量:
super_solar_panels.gui.energyPerTick=EU/t:
super_solar_panels.gui.progress=进度:
super_solar_panels.gui.tier=Tier:
super_solar_panels.gui.max=MAX
super_solar_panels.gui.storage=容量:
super_solar_panels.gui.generating=生成:
super_solar_panels.machines.spectral_solar_panelmoon=光谱太阳能
super_solar_panels.machines.singular_solar_panelmoon=奇异太阳能
super_solar_panels.machines.admin_solar_panelmoon=管理员太阳能
super_solar_panels.machines.photonic_solar_panelmoon=光子太阳能
super_solar_panels.machines.proton_solar_panelmoon=质子太阳能
super_solar_panels.machines.neutronium_solar_panelmoon=中子太阳能
super_solar_panels.machines.advanced_solar_panelmoon=高级太阳能
super_solar_panels.machines.hybrid_solar_panelmoon=混合太阳能
super_solar_panels.machines.ultimate_solar_panelmoon=中级混合太阳能
super_solar_panels.machines.quantum_solar_panelmoon=量子太阳能
super_solar_panels.machines.spectral_solar_panelsun=光谱阳光电池板
super_solar_panels.machines.singular_solar_panelsun=奇异阳光电池板
super_solar_panels.machines.admin_solar_panelsun=管理员阳光电池板
super_solar_panels.machines.photonic_solar_panelsun=光子阳光电池板
super_solar_panels.machines.proton_solar_panelsun=质子阳光电池板
super_solar_panels.machines.neutronium_solar_panelsun=中子阳光电池板
super_solar_panels.machines.advanced_solar_panelsun=高级阳光电池板
super_solar_panels.machines.hybrid_solar_panelsun=混合阳光电池板
super_solar_panels.machines.ultimate_solar_panelsun=中级阳光电池板
super_solar_panels.machines.quantum_solar_panelsun=量子阳光电池板
super_solar_panels.machines.spectral_solar_panelrain=光子雨能电池板
super_solar_panels.machines.singular_solar_panelrain=奇异雨能电池板
super_solar_panels.machines.admin_solar_panelrain=管理员雨能电池板
super_solar_panels.machines.photonic_solar_panelrain=光子雨能电池板
super_solar_panels.machines.proton_solar_panelrain=质子雨能电池板
super_solar_panels.machines.neutronium_solar_panelrain=中子雨能电池板
super_solar_panels.machines.advanced_solar_panelrain=高级雨能电池板
super_solar_panels.machines.hybrid_solar_panelrain=混合雨能电池板
super_solar_panels.machines.ultimate_solar_panelrain=终极雨能电池板
super_solar_panels.machines.quantum_solar_panelrain=量子雨能电池板
super_solar_panels.machines.nutronfabricator=中子流体生产机
item.crafting.name=手工制作
super_solar_panels.crafting.nanobox.name=纳米工具箱

**Comment by ijo42** [comment]
Discord used to coordinate localization. link in readme
