### ISSUE TITLE
The molecular recombiner in version 1.7.10 cannot be powered on in the server

### ISSUE THREAD

**Issue by Alexisfw** [ZelGimi/supersolarpanels#8]
The words may be a little strange, because I don't know much about English, so I used translation software.
The molecular recombiner in version 1.7.10 can't be used in the server by connecting any wire or generator, but I can use it in the stand-alone archive. I hope to see what the problem is.
In addition, the Chinese translation of version 1.7.10 is as follows
[zh_CN.zip](https://github.com/ZelGimi/supersolarpanels/files/5988390/zh_CN.zip)
I have translated all the parts I can translate, but I can't guarantee that they are completely correct. You can check them. Thank you

**Comment by ZelGimi** [comment]
Hi! Problem with molecular transformer i know and solved. Molecular transformator was remade fully. the Chinese translation will be in the next version (1.5RC3 ,which will be in Sunday 21.02.2021) . Thanks ,that you help this mod to develop!
