### ISSUE TITLE
On the instability of GUI interface

### ISSUE THREAD

**Issue by Alexisfw** [ZelGimi/supersolarpanels#9]
Again, I use translation software
In version 1.7.10, I found some problems. Although they are not bugs, I hope to improve them.
It's mainly about GUI interface. First of all, the energy storage progress bar of the solar panel will occasionally move back and forth, and the hell will be put in the slot. After the terminal module, the GUI style will turn red, and then it will return to normal. This cycle will stop several times until the power is full. When I use the compressor and other machines, when the compression starts but does not end, I click the empty finished product box to compress All of a sudden, the progress bar of XP is cleared, and the machine that produces XP still absorbs power after XP is full, but XP is not added. I hope it will be repaired in the next version. Thank you

**Comment by Alexisfw** [comment]
I'm sorry I wrote a part wrong
It's mainly about GUI interface. First of all, the energy storage progress bar of the solar panel will occasionally move back and forth, and the hell will be put in the slot. After the terminal module, the GUI style will turn red, and then it will return to normal. This cycle will stop several times until the power is full. When I use the compressor and other machines, when the compression starts but does not end, I click the empty finished product box to check the progress All of a sudden, it's cleared. XP machines still absorb power when XP is full, but they don't add XP. Hope to repair it in the next version. Thank you

**Comment by Alexisfw** [comment]
I found a few more bugs. You can watch the video. I fixed several mistakes in Chinese translation. The map of "chaosingot" is wrong. It is not displayed in the game. I fixed it after modifying the map file name "ChaosIngot" to "chaosingot"


https://user-images.githubusercontent.com/79145039/108156459-a880c880-711b-11eb-80cf-e003f5d97f7e.mp4


https://user-images.githubusercontent.com/79145039/108156476-b1719a00-711b-11eb-9b8c-e5e6476fc33b.mp4


https://user-images.githubusercontent.com/79145039/108156609-f269ae80-711b-11eb-81ce-eab80a1b6817.mp4


https://user-images.githubusercontent.com/79145039/108156626-f990bc80-711b-11eb-9610-0fac310c200f.mp4

[bug2.zip](https://github.com/ZelGimi/supersolarpanels/files/5993234/bug2.zip)

[zh_CN.zip](https://github.com/ZelGimi/supersolarpanels/files/5993239/zh_CN.zip)

Thank you!

**Comment by Alexisfw** [comment]
I found that the wires don't need to be electrified and there's an electric shock.
The voltage of the solar panel is too high to cause the machine to explode easily,I want to add the switch of voltage mechanism in the configuration file.
Except for the wire of IC2, the wire of other mods cannot export electricity,for example, mekanism.

**Comment by ZelGimi** [comment]
Thanks for your found bugs. Some of these we know,but thanks ,that you help mod ! I am happy,that more and more people want help of this mod!

**Comment by ZelGimi** [comment]
solved
